# fly.toml file generated for reorx-n8n on 2022-10-13T22:12:56+08:00

app = "reorx-n8n"


[build]
  image = "n8nio/n8n:0.236.0"

[env]
  DB_POSTGRESDB_DATABASE = "postgres"
  DB_POSTGRESDB_PORT = 5432
  DB_POSTGRESDB_SCHEMA = "public"
  DB_POSTGRESDB_USER = "postgres"
  DB_TYPE = "postgresdb"
  EXECUTIONS_DATA_MAX_AGE = 8
  EXECUTIONS_DATA_PRUNE = "true"
  EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS = "false"
  EXECUTIONS_DATA_SAVE_ON_ERROR = "all"
  #EXECUTIONS_DATA_SAVE_ON_PROGRESS = "false"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS = "none"
  GENERIC_TIMEZONE = "Asia/Shanghai"
  N8N_LOG_LEVEL = "verbose"
  PORT = 5678
  TZ = "Asia/Shanghai"
  VUE_APP_URL_BASE_API = "https://n8n.reorx.com/"
  WEBHOOK_URL = "https://n8n.reorx.com/"
  # secrets
  #DB_POSTGRESDB_HOST
  #DB_POSTGRESDB_PASSWORD
  #N8N_ENCRYPTION_KEY

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
